class Routes {
  static const loginscreen = '/',
      homescreen = '/homescreen',
      registerscreen = '/registerscreen',
      announcementscreen = '/announcementscreen',
      addannouncementscreen = '/addannouncementscreen',
      teamscreen = '/teamscreen',
      addteamscreen = '/addteamscreen',
      aboutscreen = '/aboutscreen',
      freedompostsscreen = '/freedompostsscreen',
      addfreedompostscreen = '/addfreedompostscreen',
      catalogentriesscreen = '/catalogentriesscreen',
      sourcecodescreen = '/sourcecodescreen',
      eventcalendarscreen = '/eventcalendarscreen',
      usersearchscreen = '/usersearchscreen',
      piechartreportscreen = '/piechartreportscreen',
      piechartsearchscreen = '/piechartsearchscreen',
      addcatalogentryscreen = '/addcatalogentryscreen',
      rewardhomescreen = '/rewardhomescreen',
      rewardviewitemscreen = '/rewardviewitemscreen',
      profilescreenreward = '/profilescreenreward',
      adminpanelscreenreward = '/adminpanelscreenreward',
      adminpostsdatascreen = '/adminpostsdatascreen',
      usersinglefreedompostscreen = '/usersinglefreedomepostscreen',
      usercontributionsscreen = '/usercontributionsscreen',
      editcatalogentryscreen = '/editcatalogentryscreen';
}
